import XCTest
@testable import OldMansBookClub

/// Decodes JSON generated by the SERVER's own serializer through the CLIENT's real decoders.
///
/// The fixtures in `Tests/contract/` are produced by `ContractFixtureTests` in the API test suite
/// using exactly the options `Program.cs` configures, and committed. So this is not a test of a
/// hand-written sample of what someone thinks the server sends — it is the actual bytes.
///
/// It closes the one gap neither side could close alone: the server has one `MessageDto`, it goes
/// out over two transports with two naming policies, and Swift has two independent mirrors of it.
/// A renamed field, an enum naming policy, a date format change — each compiles cleanly on both
/// sides and breaks exactly one transport at runtime, on a device, later.
final class ContractTests: XCTestCase {

    private func fixture(_ name: String) throws -> Data {
        let bundle = Bundle(for: type(of: self))
        let url = try XCTUnwrap(bundle.url(forResource: name, withExtension: "json"),
                                "missing fixture \(name).json — regenerate with OMBC_UPDATE_CONTRACT=1 dotnet test")
        return try Data(contentsOf: url)
    }

    /// The SignalR payload is decoded by the hub client's own JSON protocol, which is plain
    /// camelCase with no key strategy — so this mirrors that rather than APIClient's decoder.
    private var signalRDecoder: JSONDecoder { JSONDecoder() }

    // ---- REST: Message ------------------------------------------------------------------------

    func testAVoiceMessageDecodesOverRest() throws {
        let message = try APIClient.decoder.decode(Message.self, from: fixture("message_voice_rest"))

        XCTAssertEqual(message.id, UUID(uuidString: "11111111-1111-1111-1111-111111111111"))
        XCTAssertEqual(message.type, .voice)
        XCTAssertEqual(message.durationSeconds, 42)
        XCTAssertEqual(message.senderAvatarUrl, "https://storage.example/avatars/mark.jpg?sig=x")
        XCTAssertEqual(message.clientId, UUID(uuidString: "44444444-4444-4444-4444-444444444444"))
        XCTAssertEqual(message.transcript, "an on-device transcript")
        XCTAssertEqual(message.parentSenderName, "Dixie")
        XCTAssertEqual(message.reactions?.first?.emoji, "👍")
    }

    func testTheMillisecondsSurviveTheRoundTrip() throws {
        let message = try APIClient.decoder.decode(Message.self, from: fixture("message_voice_rest"))

        // 2026-09-04T15:30:45.123Z. The pagination cursor is formatted back out of this and
        // compared with `<` on the server, so a decoder that silently truncated to the second
        // would skip every message sent in that same second — "a few messages go missing
        // sometimes", which is close to unfindable in the field.
        var components = DateComponents()
        components.year = 2026; components.month = 9; components.day = 4
        components.hour = 15; components.minute = 30; components.second = 45
        components.nanosecond = 123_000_000
        components.timeZone = TimeZone(identifier: "UTC")
        let expected = try XCTUnwrap(Calendar(identifier: .gregorian).date(from: components))

        XCTAssertEqual(message.sentAt.timeIntervalSince1970, expected.timeIntervalSince1970, accuracy: 0.001)
    }

    func testTheMessageTypeEnumMatchesTheServersCapitalisation() throws {
        let message = try APIClient.decoder.decode(Message.self, from: fixture("message_voice_rest"))

        // The server emits "Voice" (the .NET enum name). Swift's raw values are capitalised to
        // match. Adding a camelCase policy to the server's JsonStringEnumConverter would make
        // every message decode as .unknown — a change that looks like tidying.
        XCTAssertEqual(message.type, .voice)
        XCTAssertNotEqual(message.type, .unknown)
    }

    func testADeletedMessageTombstoneDecodes() throws {
        let message = try APIClient.decoder.decode(Message.self, from: fixture("message_deleted_rest"))

        XCTAssertTrue(message.isDeleted)
        XCTAssertNil(message.body)
        XCTAssertNil(message.mediaUrl)
        XCTAssertEqual(message.senderId, UUID(uuidString: "00000000-0000-0000-0000-000000000000"))
    }

    func testTheNarrowClubsEndpointShapeStillDecodes() throws {
        // ClubsController.GetMessages returns far fewer fields than BooksController does, into the
        // SAME Swift type. Every one of those omissions relies on a decodeIfPresent; a single
        // `decode` slipping in would break that endpoint only.
        let message = try APIClient.decoder.decode(Message.self, from: fixture("message_minimal_rest"))

        XCTAssertEqual(message.body, "hello")
        XCTAssertNil(message.transcript)
        XCTAssertNil(message.reactions)
        XCTAssertNil(message.parentMessageId)
        XCTAssertFalse(message.isDeleted)
    }

    // ---- SignalR: ChatMessageDto ---------------------------------------------------------------

    func testTheSameServerRecordAlsoDecodesOverSignalR() throws {
        let dto = try signalRDecoder.decode(ChatMessageDto.self, from: fixture("message_voice_signalr"))

        XCTAssertEqual(dto.id, UUID(uuidString: "11111111-1111-1111-1111-111111111111"))
        XCTAssertEqual(dto.type, "Voice")
        XCTAssertEqual(dto.durationSeconds, 42)
        XCTAssertEqual(dto.transcript, "an on-device transcript")
    }

    func testTheSignalRDateStringParsesToTheSameInstantAsRest() throws {
        let rest = try APIClient.decoder.decode(Message.self, from: fixture("message_voice_rest"))
        let live = try signalRDecoder.decode(ChatMessageDto.self, from: fixture("message_voice_signalr"))

        // Two different parsers, one instant. The REST decoder tries four formats; this one
        // accepts exactly ISO-8601-with-fractional-seconds and falls back to Date() — i.e. NOW —
        // if it fails, which would place a live message at the wrong end of the chat rather than
        // failing loudly.
        XCTAssertEqual(live.sentAtDate.timeIntervalSince1970,
                       rest.sentAt.timeIntervalSince1970, accuracy: 0.001)
    }

    func testTheSignalRTombstoneDecodesDespiteItsNonOptionalFlags() throws {
        // This mirror types isDeleted and isForwarded as NON-optional, unlike the REST one which
        // defaults them. If the server ever stopped emitting either field, REST would keep working
        // and live chat would silently stop delivering messages.
        let dto = try signalRDecoder.decode(ChatMessageDto.self, from: fixture("message_deleted_signalr"))

        XCTAssertTrue(dto.isDeleted)
        XCTAssertFalse(dto.isForwarded)
        XCTAssertNil(dto.body)
    }

    // ---- REST: Book and User -------------------------------------------------------------------

    func testABookDecodes() throws {
        let book = try APIClient.decoder.decode(Book.self, from: fixture("book_rest"))

        XCTAssertEqual(book.title, "The Road")
        XCTAssertEqual(book.seriesName, "Border Trilogy")
        XCTAssertEqual(book.seriesOrder, 2)
    }

    func testAnUnknownBookStatusIsTheOneDecodeFailureWorthKnowingAbout() throws {
        // `Book.status` is a non-optional enum on the client while the server types it as a bare
        // string. There is no `unknown` fallback the way MessageType has one, so a status outside
        // future/current/past — from a seed script, manual SQL, or a future migration — makes the
        // WHOLE /books response fail to decode and blanks the library.
        //
        // The server rejects such values at the API (LibraryTests covers that), so this documents
        // the client-side consequence rather than a live bug. If a fourth status is ever wanted,
        // the client needs an unknown case FIRST, in a shipped build, before the server can emit it.
        var json = try XCTUnwrap(String(data: fixture("book_rest"), encoding: .utf8))
        json = json.replacingOccurrences(of: "\"current\"", with: "\"archived\"")

        XCTAssertThrowsError(try APIClient.decoder.decode(Book.self, from: Data(json.utf8)))
    }

    func testAUserDecodesIncludingNestedPreferences() throws {
        let user = try APIClient.decoder.decode(APIClient.UserResponse.self, from: fixture("user_rest"))

        XCTAssertEqual(user.displayName, "Mark")
        XCTAssertEqual(user.nickname, "Marky")
        XCTAssertTrue(user.isAdmin)
    }
}
